name: Yarn
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn
      - run: yarn test
      - run: yarn prod
      - run: yarn dist
      - uses: actions/upload-artifact@v2
        with:
          path:
            dist/mem-treemap*.snap
            dist/mem-treemap*.AppImage
